/*Apaga os relacionamentos existentes*/
ALTER TABLE CONTROLE_PONTO.PONTO DROP CONSTRAINT USUARIO_PONTO_FK;

/*Apaga as tabelas*/
DROP TABLE CONTROLE_PONTO.USUARIOS;
DROP TABLE CONTROLE_PONTO.PONTO;

/*Apaga as sequences*/
DROP SEQUENCE CONTROLE_PONTO.USUARIOS_ID_SEQ;
DROP SEQUENCE CONTROLE_PONTO.PONTO_ID_SEQ;

/*Criação das tabelas*/
CREATE TABLE CONTROLE_PONTO.USUARIOS (
    ID_USUARIO NUMBER NOT NULL,
    NOME VARCHAR2(255) NOT NULL,
    CPF VARCHAR2(11) NOT NULL,
    CARGO VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    DATA_CONTRATACAO DATE NOT NULL,
    CONSTRAINT USUARIOS_PK PRIMARY KEY (ID_USUARIO),
    CONSTRAINT USUARIOS_UK UNIQUE (CPF)
);

CREATE TABLE CONTROLE_PONTO.PONTO (
    ID_PONTO NUMBER NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    DATA_PONTO DATE NOT NULL,
    HORARIO_ENTRADA TIMESTAMP NOT NULL,
    HORARIO_SAIDA TIMESTAMP,
    INTERVALO MINUTE(2) DEFAULT 0,  -- Intervalo em minutos
    CONSTRAINT PONTO_PK PRIMARY KEY (ID_PONTO),
    CONSTRAINT USUARIO_PONTO_FK FOREIGN KEY (ID_USUARIO)
        REFERENCES CONTROLE_PONTO.USUARIOS (ID_USUARIO)
);

/*Criação das sequences*/
CREATE SEQUENCE CONTROLE_PONTO.USUARIOS_ID_SEQ;
CREATE SEQUENCE CONTROLE_PONTO.PONTO_ID_SEQ;

/*Garante acesso total às tabelas*/
GRANT ALL ON CONTROLE_PONTO.USUARIOS TO CONTROLE_PONTO;
GRANT ALL ON CONTROLE_PONTO.PONTO TO CONTROLE_PONTO;

ALTER USER CONTROLE_PONTO quota unlimited on USERS;
