DROP SEQUENCE CODIGO_PONTO_SEQ;

ALTER TABLE PONTO DROP CONSTRAINT FUNCIONARIOS_PONTO_FK;

DROP TABLE PONTO;
DROP TABLE FUNCIONARIOS;

CREATE TABLE FUNCIONARIOS(
    CPF VARCHAR2(11) PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    CARGO VARCHAR2(30) NOT NULL
);

CREATE TABLE PONTO(
    CODIGO_PONTO NUMBER PRIMARY KEY,
    DATA_HORA DATE DEFAULT sysdate NOT NULL,
    CPF VARCHAR2(11) NOT NULL,
    CONSTRAINT FUNCIONARIOS_PONTO_FK
        FOREIGN KEY (CPF)
        REFERENCES FUNCIONARIOS (CPF)
);

CREATE SEQUENCE CODIGO_PONTO_SEQ;
